// Ganeti Cluster ("prod") Graph for the ganetiviz arbor code.

// Object that specifies the color scheme for the "vertices"
var CLR = {
  branch:"#b2b19d",
  ganetinode:"orange",
  ganetivm:"#922E00",
  ganetinodegroup:"#a7af00"
}

var GanetiNodes = {
  "node1.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance19.example.com":{color:CLR.ganetivm, alpha:0},
  "instance13.example.com":{color:CLR.ganetivm, alpha:0},
  "instance15.example.com":{color:CLR.ganetivm, alpha:0},
  "instance27.example.com":{color:CLR.ganetivm, alpha:0},
  "instance34.example.com":{color:CLR.ganetivm, alpha:0},
  "instance25.example.com":{color:CLR.ganetivm, alpha:0},
  "instance47.example.com":{color:CLR.ganetivm, alpha:0},

  "node2.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance16.example.com":{color:CLR.ganetivm, alpha:0},
  "instance1.example.com":{color:CLR.ganetivm, alpha:0},
  "instance38.example.com":{color:CLR.ganetivm, alpha:0},
  "instance52.example.com":{color:CLR.ganetivm, alpha:0},
  "instance21.example.com":{color:CLR.ganetivm, alpha:0},
  "instance20.example.com":{color:CLR.ganetivm, alpha:0},

  "node3.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance33.example.com":{color:CLR.ganetivm, alpha:0},
  "instance29.example.com":{color:CLR.ganetivm, alpha:0},
  "instance37.example.com":{color:CLR.ganetivm, alpha:0},
  "instance10.example.com":{color:CLR.ganetivm, alpha:0},
  "instance9.example.com":{color:CLR.ganetivm, alpha:0},
  "instance41.example.com":{color:CLR.ganetivm, alpha:0},
  "instance32.example.com":{color:CLR.ganetivm, alpha:0},

  "node4.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance51.example.com":{color:CLR.ganetivm, alpha:0},
  "instance18.example.com":{color:CLR.ganetivm, alpha:0},
  "instance36.example.com":{color:CLR.ganetivm, alpha:0},
  "instance28.example.com":{color:CLR.ganetivm, alpha:0},
  "instance26.example.com":{color:CLR.ganetivm, alpha:0},
  "instance2.example.com":{color:CLR.ganetivm, alpha:0},

  "node5.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance4.example.com":{color:CLR.ganetivm, alpha:0},
  "instance45.example.com":{color:CLR.ganetivm, alpha:0},
  "instance8.example.com":{color:CLR.ganetivm, alpha:0},
  "instance7.example.com":{color:CLR.ganetivm, alpha:0},
  "instance40.example.com":{color:CLR.ganetivm, alpha:0},
  "instance49.example.com":{color:CLR.ganetivm, alpha:0},

  "node6.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance43.example.com":{color:CLR.ganetivm, alpha:0},
  "instance12.example.com":{color:CLR.ganetivm, alpha:0},
  "instance48.example.com":{color:CLR.ganetivm, alpha:0},
  "instance42.example.com":{color:CLR.ganetivm, alpha:0},
  "instance17.example.com":{color:CLR.ganetivm, alpha:0},
  "instance46.example.com":{color:CLR.ganetivm, alpha:0},

  "node7.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance3.example.com":{color:CLR.ganetivm, alpha:0},
  "instance14.example.com":{color:CLR.ganetivm, alpha:0},
  "instance50.example.com":{color:CLR.ganetivm, alpha:0},
  "instance11.example.com":{color:CLR.ganetivm, alpha:0},
  "instance23.example.com":{color:CLR.ganetivm, alpha:0},
  "instance39.example.com":{color:CLR.ganetivm, alpha:0},

  "node8.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance24.example.com":{color:CLR.ganetivm, alpha:0},
  "instance35.example.com":{color:CLR.ganetivm, alpha:0},
  "instance22.example.com":{color:CLR.ganetivm, alpha:0},
  "instance31.example.com":{color:CLR.ganetivm, alpha:0},
  "instance30.example.com":{color:CLR.ganetivm, alpha:0},
  "instance5.example.com":{color:CLR.ganetivm, alpha:0},
  "instance6.example.com":{color:CLR.ganetivm, alpha:0},
  "instance44.example.com":{color:CLR.ganetivm, alpha:0},
}

var GanetiGraphEdges = {
	"node1.example.com":{
		"instance19.example.com":{length:6},
		"instance13.example.com":{length:6},
		"instance15.example.com":{length:6},
		"instance27.example.com":{length:6},
		"instance34.example.com":{length:6},
		"instance25.example.com":{length:6},
		"instance47.example.com":{length:6},
		"node4.example.com":{length:18, width:0},
		"node6.example.com":{length:18, width:0},
		"node3.example.com":{length:18, width:0},
	},
	"node2.example.com":{
		"instance16.example.com":{length:6},
		"instance1.example.com":{length:6},
		"instance38.example.com":{length:6},
		"instance52.example.com":{length:6},
		"instance21.example.com":{length:6},
		"instance20.example.com":{length:6},
		"node8.example.com":{length:18, width:0},
		"node5.example.com":{length:18, width:2},
		"node7.example.com":{length:18, width:0},
		"node4.example.com":{length:18, width:0},
		"node3.example.com":{length:18, width:0},
	},
	"node3.example.com":{
		"instance33.example.com":{length:6},
		"instance29.example.com":{length:6},
		"instance37.example.com":{length:6},
		"instance10.example.com":{length:6},
		"instance9.example.com":{length:6},
		"instance41.example.com":{length:6},
		"instance32.example.com":{length:6},
		"node8.example.com":{length:18, width:0},
		"node7.example.com":{length:18, width:0},
		"node6.example.com":{length:18, width:0},
		"node2.example.com":{length:18, width:0},
		"node5.example.com":{length:18, width:0},
		"node1.example.com":{length:18, width:0},
	},
	"node4.example.com":{
		"instance51.example.com":{length:6},
		"instance18.example.com":{length:6},
		"instance36.example.com":{length:6},
		"instance28.example.com":{length:6},
		"instance26.example.com":{length:6},
		"instance2.example.com":{length:6},
		"node8.example.com":{length:18, width:0},
		"node2.example.com":{length:18, width:0},
		"node1.example.com":{length:18, width:0},
	},
	"node5.example.com":{
		"instance4.example.com":{length:6},
		"instance45.example.com":{length:6},
		"instance8.example.com":{length:6},
		"instance7.example.com":{length:6},
		"instance40.example.com":{length:6},
		"instance49.example.com":{length:6},
		"node2.example.com":{length:18, width:0},
		"node7.example.com":{length:18, width:0},
		"node1.example.com":{length:18, width:3},
		"node3.example.com":{length:18, width:0},
	},
	"node6.example.com":{
		"instance43.example.com":{length:6},
		"instance12.example.com":{length:6},
		"instance48.example.com":{length:6},
		"instance42.example.com":{length:6},
		"instance17.example.com":{length:6},
		"instance46.example.com":{length:6},
		"node8.example.com":{length:15, width:0},
		"node5.example.com":{length:15, width:0},
		"node2.example.com":{length:15, width:0},
		"node7.example.com":{length:15, width:2},
		"node3.example.com":{length:15, width:0},
	},
	"node7.example.com":{
		"instance3.example.com":{length:6},
		"instance14.example.com":{length:6},
		"instance50.example.com":{length:6},
		"instance11.example.com":{length:6},
		"instance23.example.com":{length:6},
		"instance39.example.com":{length:6},
		"node8.example.com":{length:18, width:0},
		"node5.example.com":{length:18, width:0},
		"node2.example.com":{length:18, width:0},
		"node4.example.com":{length:18, width:0},
		"node6.example.com":{length:18, width:2},
	},
	"node8.example.com":{
		"instance24.example.com":{length:6},
		"instance35.example.com":{length:6},
		"instance22.example.com":{length:6},
		"instance31.example.com":{length:6},
		"instance30.example.com":{length:6},
		"instance5.example.com":{length:6},
		"instance6.example.com":{length:6},
		"instance44.example.com":{length:6},
		"node7.example.com":{length:18, width:0},
		"node4.example.com":{length:18, width:0},
		"node6.example.com":{length:18, width:2},
		"node3.example.com":{length:18, width:0},
	},
}

// The Ganeti Cluster Graph Object (showing only the PrimaryNode - Instance relations)
