var CLR = {
  branch:"#b2b19d",
  ganetinode:"orange",
  ganetivm:"#922E00",
  ganetinodegroup:"#a7af00"
}

var GanetiNodes = {
  "node1.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance55.example.com":{color:CLR.ganetivm, alpha:0},
  "instance45.example.com":{color:CLR.ganetivm, alpha:0},
  "instance10.example.com":{color:CLR.ganetivm, alpha:0},
  "instance56.example.com":{color:CLR.ganetivm, alpha:0},
  "instance109.example.com":{color:CLR.ganetivm, alpha:0},
  "instance8.example.com":{color:CLR.ganetivm, alpha:0},
  "instance74.example.com":{color:CLR.ganetivm, alpha:0},
  "instance80.example.com":{color:CLR.ganetivm, alpha:0},
  "instance85.example.com":{color:CLR.ganetivm, alpha:0},
  "instance100.example.com":{color:CLR.ganetivm, alpha:0},
  "instance70.example.com":{color:CLR.ganetivm, alpha:0},
  "instance52.example.com":{color:CLR.ganetivm, alpha:0},
  "instance27.example.com":{color:CLR.ganetivm, alpha:0},
  "instance46.example.com":{color:CLR.ganetivm, alpha:0},
  "instance24.example.com":{color:CLR.ganetivm, alpha:0},
  "instance65.example.com":{color:CLR.ganetivm, alpha:0},
  "instance58.example.com":{color:CLR.ganetivm, alpha:0},
  "instance2.example.com":{color:CLR.ganetivm, alpha:0},
  "instance53.example.com":{color:CLR.ganetivm, alpha:0},
  "instance44.example.com":{color:CLR.ganetivm, alpha:0},

  "node2.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance19.example.com":{color:CLR.ganetivm, alpha:0},
  "instance13.example.com":{color:CLR.ganetivm, alpha:0},
  "instance99.example.com":{color:CLR.ganetivm, alpha:0},
  "instance62.example.com":{color:CLR.ganetivm, alpha:0},
  "instance38.example.com":{color:CLR.ganetivm, alpha:0},
  "instance105.example.com":{color:CLR.ganetivm, alpha:0},
  "instance32.example.com":{color:CLR.ganetivm, alpha:0},
  "instance37.example.com":{color:CLR.ganetivm, alpha:0},
  "instance1.example.com":{color:CLR.ganetivm, alpha:0},
  "instance25.example.com":{color:CLR.ganetivm, alpha:0},
  "instance94.example.com":{color:CLR.ganetivm, alpha:0},
  "instance95.example.com":{color:CLR.ganetivm, alpha:0},
  "instance12.example.com":{color:CLR.ganetivm, alpha:0},
  "instance89.example.com":{color:CLR.ganetivm, alpha:0},
  "instance61.example.com":{color:CLR.ganetivm, alpha:0},
  "instance49.example.com":{color:CLR.ganetivm, alpha:0},
  "instance83.example.com":{color:CLR.ganetivm, alpha:0},
  "instance87.example.com":{color:CLR.ganetivm, alpha:0},
  "instance90.example.com":{color:CLR.ganetivm, alpha:0},
  "instance36.example.com":{color:CLR.ganetivm, alpha:0},
  "instance18.example.com":{color:CLR.ganetivm, alpha:0},
  "instance7.example.com":{color:CLR.ganetivm, alpha:0},
  "instance39.example.com":{color:CLR.ganetivm, alpha:0},
  "instance40.example.com":{color:CLR.ganetivm, alpha:0},
  "instance4.example.com":{color:CLR.ganetivm, alpha:0},

  "node3.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance16.example.com":{color:CLR.ganetivm, alpha:0},
  "instance102.example.com":{color:CLR.ganetivm, alpha:0},
  "instance41.example.com":{color:CLR.ganetivm, alpha:0},
  "instance67.example.com":{color:CLR.ganetivm, alpha:0},
  "instance104.example.com":{color:CLR.ganetivm, alpha:0},
  "instance34.example.com":{color:CLR.ganetivm, alpha:0},
  "instance75.example.com":{color:CLR.ganetivm, alpha:0},
  "instance50.example.com":{color:CLR.ganetivm, alpha:0},
  "instance51.example.com":{color:CLR.ganetivm, alpha:0},
  "instance23.example.com":{color:CLR.ganetivm, alpha:0},
  "instance54.example.com":{color:CLR.ganetivm, alpha:0},
  "instance26.example.com":{color:CLR.ganetivm, alpha:0},
  "instance21.example.com":{color:CLR.ganetivm, alpha:0},
  "instance63.example.com":{color:CLR.ganetivm, alpha:0},
  "instance22.example.com":{color:CLR.ganetivm, alpha:0},
  "instance14.example.com":{color:CLR.ganetivm, alpha:0},
  "instance81.example.com":{color:CLR.ganetivm, alpha:0},
  "instance17.example.com":{color:CLR.ganetivm, alpha:0},
  "instance101.example.com":{color:CLR.ganetivm, alpha:0},
  "instance28.example.com":{color:CLR.ganetivm, alpha:0},

  "node4.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance43.example.com":{color:CLR.ganetivm, alpha:0},
  "instance107.example.com":{color:CLR.ganetivm, alpha:0},
  "instance82.example.com":{color:CLR.ganetivm, alpha:0},
  "instance57.example.com":{color:CLR.ganetivm, alpha:0},
  "instance97.example.com":{color:CLR.ganetivm, alpha:0},
  "instance48.example.com":{color:CLR.ganetivm, alpha:0},
  "instance31.example.com":{color:CLR.ganetivm, alpha:0},
  "instance76.example.com":{color:CLR.ganetivm, alpha:0},
  "instance66.example.com":{color:CLR.ganetivm, alpha:0},
  "instance29.example.com":{color:CLR.ganetivm, alpha:0},
  "instance71.example.com":{color:CLR.ganetivm, alpha:0},
  "instance33.example.com":{color:CLR.ganetivm, alpha:0},
  "instance11.example.com":{color:CLR.ganetivm, alpha:0},
  "instance60.example.com":{color:CLR.ganetivm, alpha:0},
  "instance30.example.com":{color:CLR.ganetivm, alpha:0},
  "instance106.example.com":{color:CLR.ganetivm, alpha:0},
  "instance35.example.com":{color:CLR.ganetivm, alpha:0},
  "instance78.example.com":{color:CLR.ganetivm, alpha:0},

  "node5.example.com":{color:CLR.ganetinode, shape:"dot", alpha:1},
  "instance72.example.com":{color:CLR.ganetivm, alpha:0},
  "instance73.example.com":{color:CLR.ganetivm, alpha:0},
  "instance79.example.com":{color:CLR.ganetivm, alpha:0},
  "instance108.example.com":{color:CLR.ganetivm, alpha:0},
  "instance42.example.com":{color:CLR.ganetivm, alpha:0},
  "instance92.example.com":{color:CLR.ganetivm, alpha:0},
  "instance20.example.com":{color:CLR.ganetivm, alpha:0},
  "instance88.example.com":{color:CLR.ganetivm, alpha:0},
  "instance110.example.com":{color:CLR.ganetivm, alpha:0},
  "instance96.example.com":{color:CLR.ganetivm, alpha:0},
  "instance93.example.com":{color:CLR.ganetivm, alpha:0},
  "instance6.example.com":{color:CLR.ganetivm, alpha:0},
  "instance5.example.com":{color:CLR.ganetivm, alpha:0},
  "instance77.example.com":{color:CLR.ganetivm, alpha:0},
  "instance98.example.com":{color:CLR.ganetivm, alpha:0},
  "instance86.example.com":{color:CLR.ganetivm, alpha:0},
  "instance69.example.com":{color:CLR.ganetivm, alpha:0},
  "instance84.example.com":{color:CLR.ganetivm, alpha:0},
  "instance103.example.com":{color:CLR.ganetivm, alpha:0},
  "instance64.example.com":{color:CLR.ganetivm, alpha:0},
  "instance3.example.com":{color:CLR.ganetivm, alpha:0},
  "instance15.example.com":{color:CLR.ganetivm, alpha:0},
  "instance91.example.com":{color:CLR.ganetivm, alpha:0},
  "instance68.example.com":{color:CLR.ganetivm, alpha:0},
  "instance59.example.com":{color:CLR.ganetivm, alpha:0},
  "instance9.example.com":{color:CLR.ganetivm, alpha:0},
  "instance47.example.com":{color:CLR.ganetivm, alpha:0},
  }


var GanetiGraphEdges = {
  "node1.example.com":{
    "instance55.example.com":{length:6},
    "instance45.example.com":{length:6},
    "instance10.example.com":{length:6},
    "instance56.example.com":{length:6},
    "instance109.example.com":{length:6},
    "instance8.example.com":{length:6},
    "instance74.example.com":{length:6},
    "instance80.example.com":{length:6},
    "instance85.example.com":{length:6},
    "instance100.example.com":{length:6},
    "instance70.example.com":{length:6},
    "instance52.example.com":{length:6},
    "instance27.example.com":{length:6},
    "instance46.example.com":{length:6},
    "instance24.example.com":{length:6},
    "instance65.example.com":{length:6},
    "instance58.example.com":{length:6},
    "instance2.example.com":{length:6},
    "instance53.example.com":{length:6},
    "instance44.example.com":{length:6},
    "node5.example.com":{length:15, width:3},
    "node2.example.com":{length:15, width:3},
    "node4.example.com":{length:15, width:5},
    "node3.example.com":{length:15, width:9},
  },
  "node2.example.com":{
    "instance19.example.com":{length:6},
    "instance13.example.com":{length:6},
    "instance99.example.com":{length:6},
    "instance62.example.com":{length:6},
    "instance38.example.com":{length:6},
    "instance105.example.com":{length:6},
    "instance32.example.com":{length:6},
    "instance37.example.com":{length:6},
    "instance1.example.com":{length:6},
    "instance25.example.com":{length:6},
    "instance94.example.com":{length:6},
    "instance95.example.com":{length:6},
    "instance12.example.com":{length:6},
    "instance89.example.com":{length:6},
    "instance61.example.com":{length:6},
    "instance49.example.com":{length:6},
    "instance83.example.com":{length:6},
    "instance87.example.com":{length:6},
    "instance90.example.com":{length:6},
    "instance36.example.com":{length:6},
    "instance18.example.com":{length:6},
    "instance7.example.com":{length:6},
    "instance39.example.com":{length:6},
    "instance40.example.com":{length:6},
    "instance4.example.com":{length:6},
    "node5.example.com":{length:15, width:10},
    "node4.example.com":{length:15, width:4},
    "node1.example.com":{length:15, width:6},
    "node3.example.com":{length:15, width:3},
  },
  "node3.example.com":{
    "instance16.example.com":{length:6},
    "instance102.example.com":{length:6},
    "instance41.example.com":{length:6},
    "instance67.example.com":{length:6},
    "instance104.example.com":{length:6},
    "instance34.example.com":{length:6},
    "instance75.example.com":{length:6},
    "instance50.example.com":{length:6},
    "instance51.example.com":{length:6},
    "instance23.example.com":{length:6},
    "instance54.example.com":{length:6},
    "instance26.example.com":{length:6},
    "instance21.example.com":{length:6},
    "instance63.example.com":{length:6},
    "instance22.example.com":{length:6},
    "instance14.example.com":{length:6},
    "instance81.example.com":{length:6},
    "instance17.example.com":{length:6},
    "instance101.example.com":{length:6},
    "instance28.example.com":{length:6},
    "node5.example.com":{length:15, width:7},
    "node2.example.com":{length:15, width:1},
    "node4.example.com":{length:15, width:10},
    "node1.example.com":{length:15, width:2},
  },
  "node4.example.com":{
    "instance43.example.com":{length:6},
    "instance107.example.com":{length:6},
    "instance82.example.com":{length:6},
    "instance57.example.com":{length:6},
    "instance97.example.com":{length:6},
    "instance48.example.com":{length:6},
    "instance31.example.com":{length:6},
    "instance76.example.com":{length:6},
    "instance66.example.com":{length:6},
    "instance29.example.com":{length:6},
    "instance71.example.com":{length:6},
    "instance33.example.com":{length:6},
    "instance11.example.com":{length:6},
    "instance60.example.com":{length:6},
    "instance30.example.com":{length:6},
    "instance106.example.com":{length:6},
    "instance35.example.com":{length:6},
    "instance78.example.com":{length:6},
    "node5.example.com":{length:15, width:2},
    "node2.example.com":{length:15, width:5},
    "node1.example.com":{length:15, width:6},
    "node3.example.com":{length:15, width:5},
  },
  "node5.example.com":{
    "instance72.example.com":{length:6},
    "instance73.example.com":{length:6},
    "instance79.example.com":{length:6},
    "instance108.example.com":{length:6},
    "instance42.example.com":{length:6},
    "instance92.example.com":{length:6},
    "instance20.example.com":{length:6},
    "instance88.example.com":{length:6},
    "instance110.example.com":{length:6},
    "instance96.example.com":{length:6},
    "instance93.example.com":{length:6},
    "instance6.example.com":{length:6},
    "instance5.example.com":{length:6},
    "instance77.example.com":{length:6},
    "instance98.example.com":{length:6},
    "instance86.example.com":{length:6},
    "instance69.example.com":{length:6},
    "instance84.example.com":{length:6},
    "instance103.example.com":{length:6},
    "instance64.example.com":{length:6},
    "instance3.example.com":{length:6},
    "instance15.example.com":{length:6},
    "instance91.example.com":{length:6},
    "instance68.example.com":{length:6},
    "instance59.example.com":{length:6},
    "instance9.example.com":{length:6},
    "instance47.example.com":{length:6},
    "node2.example.com":{length:15, width:12},
    "node4.example.com":{length:15, width:3},
    "node1.example.com":{length:15, width:4},
    "node3.example.com":{length:15, width:3},
  },
}

// The Ganeti Cluster Graph Object (showing only the PNode - Instance relations, PNode-SNode Relations)
